name = "dspace-uploader-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Static Assets binding for Cloudflare Workers
[assets]
directory = "./public"
binding = "ASSETS"

# Environment variables
[vars]
ENVIRONMENT = "production"
ENCRYPTION_SECRET = "dspace-edge-encryption-key-secret-2026"
