name = "dspace-uploader-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Static Assets binding for Cloudflare Workers
[assets]
directory = "./public"
binding = "ASSETS"

# Optional Cloudflare R2 Bucket for staging 100MB+ large PDFs
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "dspace-large-files"

# Environment variables
[vars]
ENVIRONMENT = "production"
ENCRYPTION_SECRET = "dspace-edge-encryption-key-secret-2026"
